### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by iAnonymous3000**
Switch to AGPLv3 to ensure network service providers must share modifications. This protects our community's interests in cloud/SaaS deployments while maintaining commercial usability. This closes the ASP loophole and preserving our commitment to open source collaboration.

### CODE REVIEW

**Comment by pdurbin** [comment]
I didn't think that hard about a license. The original discussion is here:

- #4

As I wrote there, "I don't feel strongly about which license but in https://github.com/bostonopen/bostonopen.github.io/commit/9e240d863a46875fe998af7c484d718ae5f186da I added Apache because it's what we use at work. 🤷"

Shall we debate the merits of copyleft vs. permissive licenses? 😄 

Also, I'd like to understand the problems we're trying to solve.

Are we worried that a big company will use our code (of which there is basically none, yet) in a service they host and not share back any changes? I'm not especially worried about this.

Are we worried that Apache is 2 is not open source enough? It certainly is. I mean, Apache 2 is a legit open source license.

Are there other problems we're trying to solve that I'm not understanding?

If we switch, do we introduce different problems? Copyleft licenses like the GPL and the AGPL are viral. We basically don't have any code yet, but if we do, some people and project might not want to adopt our code because it would force them to change their code to a copyleft license.

I hope this helps. I'm not saying I'll never use a copyleft license but in recent years I've been convinced by the arguments for permissive licenses. They are much more relaxed. Live and let live. Also, I'm certainly not an expert in licenses! 😅

**Comment by ShaneCurcuru** [comment]
While I'm new here, I'm wondering: am I missing something about the code the community plans to build in this repo?  It really seems like a website and for pointing out ideas from the meetups.

Unless there's a specific expectation and agreement that the repo will be hosting actual code meant for wide re-use, and the community agrees that copyleft is more important to protect from others using it, vs. permissive which has that risk, but also has a larger body of potential contributors.  I don't get a vote here, but I'd stick with Apache-2.0.

**Comment by pdurbin** [comment]
@ShaneCurcuru so far we're pretty good at showing up at a bar and having a drink or two. 😄 

That said, it might be nice to collaborate on some code some day. Wide re-use? I doubt it. Who knows!

@iAnonymous3000 I understand what you mean about setting a tone. @ShaneCurcuru actually encourage us to create a LICENSE file in the first place, in #4. It's probably better to have any open source license than nothing. I think it comes down to whether we want to set the tone as copyleft or not. 🤷 I like to think we can enjoy each other's company either way. 🍻

**Comment by iAnonymous3000** [comment]
I get the point about the current scope being limited, but I think choosing AGPLv3 now sets a strong precedent if the project grows into something more code-heavy. It ensures we keep things fair and collaborative long-term. That said, I’m open to sticking with Apache 2.0 for now and revisiting later if needed. 

I’ll close this PR for now—I’m no license expert and don’t want to overcomplicate things at this stage. Appreciate all the input!

**Comment by pdurbin** [comment]
Another thought: there's always dual-licensing. I haven't tried having multiple license files but I see an interesting suggestion here: https://softwareengineering.stackexchange.com/questions/304874/declaring-multiple-licences-in-a-github-project/371435#371435

**Pull request closed without merging**
